const data = {
  product: [
    {
      name: 'Nike slim shirt',
      slug: 'nike slim shirt',
      category: 'Shirt',
      image: '/image/p1.jpg',
      price: 1200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike slim shirt',
      category: 'Shirt',
      image: '/image/p1.jpg',
      price: 1200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim pant',
      slug: 'nike slim pant',
      category: 'pant',
      image: '/image/p3.jpg',
      price: 1100,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pant',
    },
    {
      name: 'Nike slim pant',
      slug: 'nike slim pant',
      category: 'pant',
      image: '/image/p4.jpg',
      price: 1500,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pant',
    },
  ],
};
